# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command or created alongside the database with db:setup)
#
# Examples:

Product.create name: 'Adobe bread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Amish friendship bread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Anadama bread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Banana bread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Beaten biscuit', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Biscuit', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Brown bread', time_to_bake_in_seconds: 15 * 60 + rand(600)
Product.create name: 'Bulkie roll', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Cornbread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Cuban bread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Frybread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Graham bread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Hot water corn bread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Hushpuppy', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Muffin', time_to_bake_in_seconds: 15 * 60 + rand(600)
Product.create name: 'Muffuletta', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Parker House roll', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Pepperoni roll', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Popover', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Pullman loaf', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Salt-rising bread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Scali bread', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Sloosh', time_to_bake_in_seconds: 25 * 60 + rand(600)
Product.create name: 'Texas toast', time_to_bake_in_seconds: 15 * 60 + rand(600)

Product.create name: 'Angel food cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Apple cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Applesauce cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Aranygaluska', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Avocado cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Babka', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Ballokume', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Banana cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Basbousa', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Beer cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Better than sex cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Boston cream pie', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Banana cake/bread', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Banoffee pie', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Bara brith', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Battenberg cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Baumkuchen', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Bibingka', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Bienenstich Bee Sting', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Birthday cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Bizcocho Dominicano', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Black Forest cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Blitztorte', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Blondie', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Bolo de mel', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Brazil nut cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Brownie', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Buccellato', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Budapestlängd', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Bundt cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Butter cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Butterfly cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Cassata', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Carrot cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Cheesecake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Chestnut cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Chiffon cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Chocolate cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Christmas cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Clementine cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Coconut cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Coffee cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Cremeschnitte', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Croquembouche', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Crystal cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Cuatro leches cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Cucumber cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Cupcake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Dacquoise', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Date and walnut loaf', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Date square', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Depression cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: "Devil's food cake", time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Dobos cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Dundee cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Eccles cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Esterházy torte', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Fat rascal', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Faworki', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Fig cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Financier', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Flourless chocolate cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Fondant Fancy', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Fragelité', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Frog cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Fruitcake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Fountain cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Funing big cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Genoa cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Genoise Genoese cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'German Chocolate Cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Gingerbread', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Goose Breast', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Halloween cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Hash brownies', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Hot milk cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Ice cream cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Jaffa Cakes', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Kabuni', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Karpatka', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Kiev cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'King cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Kladdkaka', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Kliņģeris', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Kołacz', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Kolaczki', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Kouign-amann', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Kutia', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Kransekake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Kremówka', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Krówka', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Lady Baltimore cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Lamanki or Klamäti', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Lamington', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Layer cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Lemon cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Madeira cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Makowiec', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Magdalena', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Mantecada', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Marble cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Mazurek', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Merveilleux', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Mille-feuille', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Misérable cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Molten chocolate cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Mooncake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Muffin', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Napoleonshat', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Napeleonskake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Nasturtium cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Onion cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Oponki or Pączki', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Opera cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Orange and polenta cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Othellolagkage', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Pan di Spagna', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Pancake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Panpepato', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Panettone', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Parkin', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Pavlova', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Petit Gâteau', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Petits fours', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Piernik', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Plum cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Pound cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Princess cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Prinzregententorte', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Pumpkin bread', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Punschkrapfen', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Queen Elizabeth cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Qumeshtore me pete', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Red bean cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Red velvet cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Rum cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Rum baba', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Ruske kape', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Sachertorte', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Šakotis', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Salzburger Nockerl', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Sekacz', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Sernik', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Sesame seed cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Sfouf', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Simnel cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Smoked salmon cheesecake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Smörgåstårta', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Snowball cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Snow skin mooncake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Soufflé', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Spekkoek', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Spice cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Spit cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Sponge cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'St. Honoré cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Stack cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Strawberry cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Streuselkuchen', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Studenterbrød', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Sultana and cherry cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Suncake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Swiss roll', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Tarte Tatin', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Tea loaf', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Teacake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Tiramisu', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Tompouce', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Torta Tre Monti', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Tres leches cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Tunis cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Træstammer', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Upside-down cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Victoria sponge cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Vínarterta', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Wedding cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Welsh cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Whoopie pies', time_to_bake_in_seconds: 45 * 60 + rand(600)
Product.create name: 'Wine cake', time_to_bake_in_seconds: 45 * 60 + rand(600)
